diff --git a/channels/Makefile b/channels/Makefile
index 2d243d2262..4cbed9c985 100644
--- a/channels/Makefile
+++ b/channels/Makefile
@@ -26,11 +26,13 @@ endif
 $(call MOD_ADD_C,chan_iax2,$(wildcard iax2/*.c))
 iax2/parser.o: _ASTCFLAGS+=$(call get_menuselect_cflags,MALLOC_DEBUG)
 
+$(call MOD_ADD_C,chan_sip,$(wildcard sip/*.c))
 $(call MOD_ADD_C,chan_pjsip,$(wildcard pjsip/*.c))
 $(call MOD_ADD_C,chan_dahdi,$(wildcard dahdi/*.c) sig_analog.c sig_pri.c sig_ss7.c)
 
 chan_dahdi.o: _ASTCFLAGS+=$(call get_menuselect_cflags,LOTS_OF_SPANS)
 chan_unistim.o: _ASTCFLAGS+=$(AST_NO_FORMAT_TRUNCATION)
 chan_phone.o: _ASTCFLAGS+=$(AST_NO_FORMAT_TRUNCATION)
+chan_sip.o: _ASTCFLAGS+=$(AST_NO_FORMAT_TRUNCATION)
 
 $(call MOD_ADD_C,console_video.c vgrabbers.c console_board.c)
