# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Since this code is not updated often, retest periodically to ensure nothing has broken
  schedule:
    - cron: '0 1 15 * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  vm:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: debian:12

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - name: Checkout
       uses: actions/checkout@v2
     # Runs a set of commands using the runners shell
     # Intentionally installs directly, rather than using PhreakScript, for a more targeted CI
     - name: Build chan_sip
       run: |
          echo Beginning build
          apt-get update -y
          apt-get install -y libedit-dev git wget
          cd /usr/src
          git clone --depth 1 https://github.com/asterisk/asterisk.git
          mv asterisk asterisk-master
          cd asterisk-master
          wget https://raw.githubusercontent.com/InterLinked1/chan_sip/master/chan_sip_reinclude.sh
          chmod +x chan_sip_reinclude.sh
          ./chan_sip_reinclude.sh
          ./contrib/scripts/install_prereq install
          ./configure --enable-dev-mode --with-jansson-bundled
          make menuselect.makeopts
          menuselect/menuselect --enable chan_sip menuselect.makeopts
          menuselect/menuselect --disable res_pjsip --disable chan_pjsip menuselect.makeopts
          menuselect/menuselect --disable pbx_ael --disable pbx_lua menuselect.makeopts
          make channels
          make
          make install
          make samples
          sed -i 's/noload = chan_sip.so/load = chan_sip.so/' /etc/asterisk/modules.conf
     - name: Install PhreakScript
       run: |
          wget https://raw.githubusercontent.com/InterLinked1/phreakscript/master/phreaknet.sh
          # Create on same partition to avoid invalid cross-device link error
          mv phreaknet.sh /usr/local/src
          chmod +x /usr/local/src/phreaknet.sh
          /usr/local/src/phreaknet.sh make
     - name: Build test suite
       run: |
          phreaknet installts
          cp -r /usr/src/chan_sip/testsuite/tests/channels/SIP/ /usr/src/testsuite/tests/channels
          cp -r /usr/src/chan_sip/testsuite/tests/fax/sip /usr/src/testsuite/tests/fax
          cp /usr/src/chan_sip/testsuite/tests.diff /usr/src/testsuite
          cd /usr/src/testsuite
          git apply tests.diff
          # Make scripts executable or they'll get skipped ("FAILED TO EXECUTE... it must exist and be executable)
          chmod -R 777 tests
     - name: Run tests
       run: |
          pwd
          ls -la
          cd /usr/src/testsuite
          # Skip sip_tls_call and sip_tls_register since those fail out of the box
          ./runInVenv.sh python3 /usr/src/testsuite/runtests.py --test=tests/channels/SIP -T "sip_tls_*"
          ./runInVenv.sh python3 /usr/src/testsuite/runtests.py --test=tests/fax/sip
